version: "3.8"
services:
    proxy:
        build:
            context: ./proxy
            dockerfile: Dockerfile
        depends_on:
            - web
        restart: always
        ports:
            - "80:80"
            - "443:443"

    web:
        build:
            context: ./web
            dockerfile: Dockerfile
        restart: always
